Repository WildCodeSchool/Rogue-One_Symfony, pull requests merged in 2024-02, with the labels that each got.

#1 Creation of the database and the entities
  .gitignore
  composer.lock
  migrations/Version20240219145857.php
  src/Entity/Category.php
  src/Entity/Contact.php
  src/Entity/Product.php
  src/Repository/CategoryRepository.php
  src/Repository/ContactRepository.php
  src/Repository/ProductRepository.php
Labels: enhancement

#5 Migration page Contact and css
  assets/styles/pages/contact.css
  src/Controller/ContactController.php
  templates/contact/index.html.twig
Labels: enhancement

#9 Migration of page Home with css
  assets/styles/pages/banner.css
  src/Controller/HomeController.php
  templates/home/index.html.twig
Labels: enhancement

#10 Migration of page show Mocktail with css
  assets/styles/pages/mocktail_show.css
  src/Controller/MocktailController.php
  templates/base.html.twig
  templates/mocktail/show.html.twig
Labels: enhancement

#4 Migration page index of Mocktail, set css and js
  assets/js/mocktailsFilter.js
  assets/styles/pages/mocktails.css
  src/Controller/MocktailController.php
  templates/mocktail/index.html.twig
Labels: enhancement

#18 Add Navbar
  templates/home/index.html.twig
Labels: bug

#17 Add images
  assets/images/banner-01.jpg
  assets/images/banner-02.jpg
  assets/images/banner-03.jpg
  assets/images/banner/Banniere.jpg
  assets/images/logo.png
  assets/images/mocktails/hotBlood.png
  assets/images/mocktails/hotPapaChewi.png
  assets/images/mocktails/iceCoffeeGinger.png
  assets/images/mocktails/macoci.png
  assets/images/mocktails/melojaGinger.png
  assets/images/mocktails/morinas.png
  assets/images/mocktails/pangaRouj.png
  assets/images/mocktails/papayerPeyi.png
  assets/images/mocktails/solojah.png
  assets/images/mocktails/thePeyiDore.png
  assets/images/mocktails/waraTail.png
  assets/images/mocktails/wassaiTail.png
  assets/images/mocktails/yanaStart.png
  assets/images/team/member1.png
  assets/images/team/member3.png
  assets/images/v966-23.jpg
Labels: enhancement

#21 Update mocktailController and index
  assets/styles/pages/mocktail.css
  src/Controller/MocktailController.php
  templates/base.html.twig
  templates/mocktail/index.html.twig
Labels: documentation

#20 Fixtures
  assets/images/team/member2.png
  assets/images/team/membre2.png
  composer.json
  composer.lock
  src/DataFixtures/AppFixtures.php
  src/DataFixtures/CategoryFixtures.php
  src/DataFixtures/ProductFixtures.php
  src/Entity/Product.php
  templates/about_us/index.html.twig
  templates/base.html.twig
  templates/home/index.html.twig
  templates/mocktail/show.html.twig
Labels: documentation

#23 Add form, working needs a bit of adjustement and better css
  src/Controller/ContactController.php
  src/Form/ContactType.php
  templates/contact/index.html.twig
Labels: enhancement

#24 Update table mocktail into product and controller adjustement
  .gitignore
  assets/app.js
  assets/images/team/member2.png
  assets/images/team/membre2.png
  assets/js/fillters.js
  assets/js/mocktailFilter.js
  assets/js/mocktailsFilter.js
  assets/js/navbar.js
  src/Controller/ProductController.php
  templates/partials/_navbar.html.twig
  templates/product/index.html.twig
  templates/product/show.html.twig
Labels: enhancement

#25 Update rename controler and index and add show controller and route
  composer.json
  composer.lock
  src/Controller/ProductController.php
  templates/partials/_navbar.html.twig
  templates/product/index.html.twig
Labels: documentation, enhancement

#30 CRUD Created For Category
  src/Controller/AdminCategoryController.php
  src/Form/CategoryType.php
  templates/admin/index.html.twig
  templates/admin_category/_delete_form.html.twig
  templates/admin_category/_form.html.twig
  templates/admin_category/edit.html.twig
  templates/admin_category/index.html.twig
  templates/admin_category/new.html.twig
  templates/admin_category/show.html.twig
Labels: enhancement

#31 CRUD Created for Product
  src/Controller/AdminProductController.php
  src/Form/ProductType.php
  templates/admin/index.html.twig
  templates/admin_product/_delete_form.html.twig
  templates/admin_product/_form.html.twig
  templates/admin_product/edit.html.twig
  templates/admin_product/index.html.twig
  templates/admin_product/new.html.twig
  templates/admin_product/show.html.twig
Labels: enhancement

#29 Update fix
  assets/about-us.js
  assets/admin.js
  assets/app.js
  assets/contact.js
  assets/home.js
  assets/mocktail_index.js
  assets/mocktail_show.js
  assets/styles/components/banner.css
  assets/styles/components/global.css
  assets/styles/components/header.css
  assets/styles/layout.css
  assets/styles/pages/admin.css
  assets/styles/pages/show_mocktail.css
  templates/about_us/index.html.twig
  templates/admin/index.html.twig
  templates/base.html.twig
  templates/contact/index.html.twig
  templates/home/index.html.twig
  templates/product/index.html.twig
  templates/product/show.html.twig
  webpack.config.js
Labels: documentation, enhancement

#45 Restore deleted global.css file
  assets/styles/global.css
Labels: documentation, enhancement

#47 Fix index contact and css
  assets/admin.js
  assets/styles/pages/contact.css
  templates/contact/index.html.twig
  webpack.config.js
Labels: documentation, enhancement

#51 PR-Navbar_&_Footer
  assets/styles/components/footer.css
  assets/styles/components/navbar.css
  templates/partials/_footer.html.twig
  templates/partials/_navbar.html.twig
Labels: enhancement

#50 PR - CSS & PNG
  assets/images/mc_logo_favicon.png
  assets/images/mc_logo_no_text.png
  assets/images/mc_logo_text.png
  assets/images/v966-23.jpg
  assets/images/video-frame.jpg
  assets/styles/components/banner.css
  assets/styles/pages/admin.css
  templates/base.html.twig
Labels: enhancement

#48 PR - Page Home
  assets/styles/global.css
  assets/styles/pages/home.css
  templates/home/index.html.twig
Labels: enhancement

#49 PR - Page Mocktail
  assets/styles/pages/mocktail.css
  templates/product/show.html.twig
Labels: enhancement

#52 Create the controller admin contact and templates
  src/Controller/AdminContactController.php
  templates/admin.base.html.twig
  templates/admin_category/index.html.twig
  templates/admin_category/show.html.twig
  templates/admin_contact/index.html.twig
  templates/admin_contact/show.html.twig
  templates/partials/_footer.html.twig
Labels: documentation, enhancement

#53 Add the button
  assets/styles/admin/adminDashboard.css
  templates/admin_category/index.html.twig
  templates/admin_category/new.html.twig
  templates/admin_product/index.html.twig
  templates/admin_product/new.html.twig
Labels: documentation, enhancement

#57 Product schema changes for image file and category name
  assets/styles/admin/adminDashboard.css
  src/Entity/Product.php
  src/Form/ProductType.php
  templates/admin_product/index.html.twig
Labels: documentation

#58 -- hotfix
  assets/styles/global.css
  src/Controller/HomeController.php
  src/Controller/ProductController.php
  src/Repository/ProductRepository.php
  templates/faq/index.html.twig
  templates/home/index.html.twig
  templates/member/index.html.twig
  templates/partials/_footer.html.twig
  templates/product/show.html.twig
Labels: bug
